apiVersion: v1
kind: Pod
metadata:
  name: dry-agent
spec:
  containers:
    - name: hushcrumbs
      image: localhost/dry-agent/hushcrumbs
      env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: hushcrumbs-secret
              key: ENCRYPTION_KEY
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: hushcrumbs-secret
              key: API_TOKEN
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: hushcrumbs-data
          mountPath: /data
    - name: app
      image: localhost/dry-agent/app
      env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: hushcrumbs-secret
              key: API_TOKEN
        - name: APP_HOST
          value: localhost
        - name: APP_PORT
          value: ${APP_PORT}
      ports:
        - containerPort: 80
          hostPort: ${APP_PORT}
      volumeMounts:
        - name: workstation-data
          mountPath: /root
  volumes:
    - name: hushcrumbs-data
      persistentVolumeClaim:
        claimName: hushcrumbs-pvc
    - name: workstation-data
      persistentVolumeClaim:
        claimName: workstation-pvc
