apiVersion: v1
kind: Pod
metadata:
  name: dry-agent
spec:
  containers:
    - name: hushcrumbs
      image: localhost/enigmacurry/hushcrumbs
      env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: hushcrumbs-secret
              key: ENCRYPTION_KEY
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: hushcrumbs-secret
              key: API_TOKEN
      ports:
        - containerPort: 80
      volumeMounts:
        - name: hushcrumbs-data
          mountPath: /data
  volumes:
    - name: hushcrumbs-data
      persistentVolumeClaim:
        claimName: hushcrumbs-pvc
