model_list:
  - model_name: assistant
    litellm_params:
      model: os.environ/OPENAI_MODEL_ASSISTANT
      api_base: os.environ/OPENAI_BASE_URL
      api_key: os.environ/OPENAI_API_KEY
      rpm: 6
  - model_name: lite
    litellm_params:
      model: os.environ/OPENAI_MODEL_LITE
      api_base: os.environ/OPENAI_BASE_URL
      api_key: os.environ/OPENAI_API_KEY
      rpm: 6
