tls:
  certificates:
    - certFile: /certs/dry-agent_Traefik.crt
      keyFile: /certs/dry-agent_Traefik.key

http:
  serversTransports:
    secure-backends:
      rootCAs:
        - /certs/dry-agent-root.crt
      certificates:
        - certFile: /certs/dry-agent_Traefik.crt
          keyFile: /certs/dry-agent_Traefik.key

  routers:
    app-router:
      rule: "(Host(`${PUBLIC_HOST}`) || Host(`127.0.0.1`) || Host(`::1`)) && (PathPrefix(`/api/`) || Path(`/docs`) || Path(`/get-login-url`) || Path(`/openapi.json`))"
      entryPoints: ["websecure"]
      service: app-service
      tls: {}
      middlewares:
        - app-allowlist
        - dry-agent-auth

    app-login:
      rule: "(Host(`${PUBLIC_HOST}`) || Host(`127.0.0.1`) || Host(`::1`)) && Path(`/login`) || Path(`/logout`)"
      entryPoints: ["websecure"]
      service: app-service
      tls: {}
      middlewares:
        - app-allowlist

    totp-router:
      rule: "(Host(`${PUBLIC_HOST}`) || Host(`127.0.0.1`) || Host(`::1`)) && PathPrefix(`/totp`)"
      entryPoints: ["websecure"]
      service: auth-service
      tls: {}
      middlewares:
        - app-allowlist
        - set-x-forwarded-proto

    frontend-router:
      rule: "(Host(`${PUBLIC_HOST}`) || Host(`127.0.0.1`) || Host(`::1`)) && PathPrefix(`/`)"
      entryPoints: ["websecure"]
      service: frontend-service
      tls: {}
      middlewares:
        - app-allowlist
        - dry-agent-auth

  services:
    app-service:
      loadBalancer:
        passHostHeader: true
        serversTransport: secure-backends
        servers:
          - url: "https://127.0.0.1:${APP_LOCALHOST_PORT}"

    frontend-service:
      loadBalancer:
        passHostHeader: true
        serversTransport: secure-backends
        servers:
          - url: "https://127.0.0.1:${FRONTEND_LOCALHOST_PORT}"

    auth-service:
      loadBalancer:
        passHostHeader: true
        serversTransport: secure-backends
        servers:
          - url: "https://127.0.0.1:${AUTH_LOCALHOST_PORT}"

  middlewares:
    app-allowlist:
      ipAllowList:
        sourceRange:
          - "${PUBLIC_SUBNET}"
    dry-agent-auth:
      forwardAuth:
        address: "https://127.0.0.1:${AUTH_LOCALHOST_PORT}/auth"
        trustForwardHeader: true
        tls:
          ca: "/certs/dry-agent-root.crt"
          cert: "/certs/dry-agent_Traefik.crt"
          key: "/certs/dry-agent_Traefik.key"
    set-x-forwarded-proto:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
tcp:
  routers:
    ssh-router:
      entryPoints:
        - ssh
      rule: "HostSNI(`*`)"
      service: ssh-service
      middlewares:
        - ssh-allowlist

  services:
    ssh-service:
      loadBalancer:
        servers:
          - address: "127.0.0.1:${SSH_LOCALHOST_PORT}"

  middlewares:
    ssh-allowlist:
      ipAllowList:
        sourceRange:
          - "${PUBLIC_SUBNET}"
