[tool.poetry]
name = "app"
version = "0.1.0"
description = "dry_agent webapp"
authors = ["EnigmaCurry <ryan@enigmacurry.com>"]

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115"
uvicorn = "^0.34"
jinja2 = "^3.1.6"

[tool.poetry.group.dev.dependencies]
